### PR TITLE
Add doctrine event listener that will process persisted/updated images

### PR DESCRIPTION
**Pull request by loevgaard**
Related #9

### CODE REVIEW

**Comment by leflings** [comment]
I think it should be left as a choice for the plugin user, whether they want to attach/create listeners?

**Comment by loevgaard** [comment]
@leflings: Done in the last commit :)

**Comment by leflings** [comment]
> @leflings: Done in the last commit :)

I'd prefer `false` as default - element of least surprise in my opinion :)

The listener should also listen on delete events and cleanup files on disk when that happens? Maybe a separate issue?

**Comment by loevgaard** [comment]
HEre is an issue for that: https://github.com/Setono/SyliusImagePlugin/issues/15

**Review by leflings — APPROVED** [review]
I'm principally opposed to everything, just for the record, but I'll let this one slide ;)

**Pull request merged**
